[workspace]
members = [
    "util",
    "parser",
    #"y2020",
    #"y2021",
    "y2022",
    "y2019",
]

[profile.release]
opt-level = 3
debug = false
lto = "fat"
panic = "abort"
incremental = false
codegen-units = 1
